### ISSUE TITLE
Seller can add a product to sell

### ISSUE THREAD

**Issue by hannahhall** [Holyhead-Harpies/Bangazon-Ruby-on-Rails-Web-Interface#1]
**Given** the user can filled in all fields of the product form with valid information
**When** the user clicks the *Sell* button
**Then** the user will be redirected to the product detail view for that product

**Given** the user can filled in all fields of the product form with any invalid information
**When** the user clicks the *Sell* button
**Then** the user will be immediately notified with error information for each invalid value

**Comment by beelarr** [comment]
When the user clicks on the Sell a product button in the menu bar
Then the user will be presented with a product form

**Comment by beelarr** [comment]
Auth of this ticket has been seperated to #45
