### ISSUE TITLE
User can view product detail

### ISSUE THREAD

**Issue by hannahhall** [Holyhead-Harpies/Bangazon-Ruby-on-Rails-Web-Interface#13]
**Given** user is viewing any page that contains a hyperlink for a product
**When** user performs a gesture on the product hyperlink
**Then** user will be shows the product detail page containing title, description, quantity available,  price/unit, and a button labeled *Add to Order*

**Given** 1+ users have purchased a product
**When** a user views the details
**Then** the quantity display should show how many are remaining, not how many were originally for sale

**Comment by beelarr** [comment]
No authenticated, but when they click on "Add to Order" prompts user to log in.

**Comment by drteresavasquez** [comment]
I have updated the product details and added the add to order button, but it is not linking anywhere.
