### ISSUE TITLE
Seller can upload a image of the product

### ISSUE THREAD

**Issue by hannahhall** [Holyhead-Harpies/Bangazon-Ruby-on-Rails-Web-Interface#14]
**Given** the user is uploading a product
**When** the user clicks "upload photo"
**And** selects a file
**Then** a thumbnail of the image will show in the Product Detail view

**Comment by tedpennington** [comment]
To consider: https://code.tutsplus.com/tutorials/rails-image-upload-using-carrierwave-in-a-rails-app--cms-25183

**Comment by tedpennington** [comment]
https://infinum.co/the-capsized-eight/best-rails-image-uploader-paperclip-carrierwave-refile

**Comment by beelarr** [comment]
Included resizing
